# This Dockerfile is for development container

FROM golang:latest as builder

ENV IPADIC_URL https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM
ENV TMP_SQL_DIR /tmp/sqlite
ENV SQL_NAME words.sqlite3

RUN mkdir /go/src/apiserver
# log-in
WORKDIR /go/src/apiserver

# copy files from host to container
ADD . /go/src/apiserver

RUN apt-get update \
    && apt-get install -y sqlite3 libsqlite3-dev \
    && apt-get clean

# create sqlite from mecab ipadic
RUN wget -O ipadic.tar.gz ${IPADIC_URL} \
    && tar zxf ipadic.tar.gz \
    && mkdir -p ${TMP_SQL_DIR} \
    && COPY_TO=${TMP_SQL_DIR} SQL_NAME=${SQL_NAME} db/setup-db.bash

# db to binary dir
RUN cp ${TMP_SQL_DIR}/${SQL_NAME} ./main
